import {describe,it,expect,beforeAll,afterAll,vi} from 'vitest';
import express from 'express';
import cookieParser from 'cookie-parser';
import request from 'supertest';
import sharp from 'sharp';
import {PrismaClient} from '@prisma/client';
import {prisma,signToken} from '../middleware/auth.js';
import routes from '../routes/advertisements.js';
const run=process.env.RUN_INTEGRATION==='1';
const app=express();app.use(express.json({limit:'2mb'}));app.use(cookieParser());app.use('/ads',routes);app.use((e,_req,res,_next)=>res.status(e.status||500).json({message:e.message}));
let owner,viewer,ownerCookie,viewerCookie;
const day=new Date().toISOString().slice(0,10);
const ad={advertiser:'Integration test only',headline:'Creative',body:'Test content',url:'https://example.com',seconds:15,active:true,startsAt:day,endsAt:day};
beforeAll(async()=>{
  if(!run)return;
  owner=await prisma.user.create({data:{email:'ads-owner-integration@example.invalid',password:'not-a-login-password',role:'user'}});
  viewer=await prisma.user.create({data:{email:'ads-viewer-integration@example.invalid',password:'not-a-login-password',role:'admin'}});
  process.env.OWNER_USER_ID=owner.id;
  ownerCookie='ss_token='+signToken(owner);viewerCookie='ss_token='+signToken(viewer);
  const bytes=await sharp({create:{width:12,height:8,channels:3,background:'blue'}}).png().toBuffer();
  ad.image='data:image/png;base64,'+bytes.toString('base64');
});
afterAll(async()=>{
  vi.restoreAllMocks();
  if(!run)return;
  await prisma.$executeRaw`DELETE FROM advertisement_events`;
  await prisma.$executeRaw`DELETE FROM advertisements`;
  await prisma.user.deleteMany({where:{id:{in:[owner.id,viewer.id]}}});
  await prisma.$disconnect();
});
describe.skipIf(!run)('real PostgreSQL advertisement persistence and visibility',()=>{
  it('persists distinct creatives, excludes paused/future flights, dedupes concurrent events and retains removed statistics',async()=>{
    const first=await request(app).post('/ads/owner').set('Cookie',ownerCookie).send({...ad,creative:'first'});
    const second=await request(app).post('/ads/owner').set('Cookie',ownerCookie).send({...ad,creative:'second',seconds:30});
    expect(first.status).toBe(201);expect(second.status).toBe(201);
    expect(first.body.id).not.toBe(second.body.id);
    expect((await request(app).post('/ads/owner').set('Cookie',viewerCookie).send(ad)).status).toBe(403);
    await request(app).post('/ads/owner').set('Cookie',ownerCookie).send({...ad,creative:'paused',active:false});
    await request(app).post('/ads/owner').set('Cookie',ownerCookie).send({...ad,creative:'future',startsAt:'2099-01-01',endsAt:'2099-01-07'});
    const rotation=await request(app).get('/ads').set('Cookie',viewerCookie);
    expect(rotation.body.map(a=>a.creative)).toEqual(['first','second']);
    expect(rotation.body[0]).not.toHaveProperty('image');
    const originalImage=await request(app).get(`/ads/${first.body.id}/image`).set('Cookie',viewerCookie);
    expect(originalImage.headers['content-type']).toContain('image/webp');
    expect(rotation.body[0].revision).toBe(1);
    const ticket=rotation.body[0].ticket;
    await new Promise(resolve=>setTimeout(resolve,1100));
    const event=kind=>request(app).post(`/ads/${first.body.id}/events`).set('Cookie',viewerCookie).send({kind,ticket});
    const events=await Promise.all(Array.from({length:6},()=>event('impression')));
    expect(events.filter(r=>r.body.counted)).toHaveLength(1);
    const clicked=await event('click');expect(clicked.body.url).toBe('https://example.com/');expect(clicked.body.counted).toBe(true);
    const now=Date.now();vi.spyOn(Date,'now').mockReturnValue(now+61000);
    expect((await event('impression')).body.counted).toBe(false);
    vi.restoreAllMocks();
    // A fresh connection reads the same durable rows; no process-local Map.
    const fresh=new PrismaClient();
    const persisted=await fresh.$queryRaw`SELECT kind,viewer FROM advertisement_events WHERE ad_id=${first.body.id}`;
    await fresh.$disconnect();
    expect(persisted).toHaveLength(2);expect(persisted[0].viewer).not.toBe(viewer.id);
    let listed=await request(app).get('/ads/owner/list').set('Cookie',ownerCookie);
    expect(listed.body.find(r=>r.id===first.body.id).stats).toMatchObject({impressions:1,clicks:1,viewers:1});
    expect(listed.body.find(r=>r.id===first.body.id).daily).toHaveLength(2);
    expect(JSON.stringify(listed.body)).not.toContain(viewer.email);
    const replacement=await sharp({create:{width:12,height:8,channels:3,background:'green'}}).png().toBuffer();
    const changed=await request(app).put(`/ads/owner/${first.body.id}`).set('Cookie',ownerCookie).send({...ad,image:'data:image/png;base64,'+replacement.toString('base64')});
    expect(changed.status).toBe(200);
    const editedImage=await request(app).get(`/ads/${first.body.id}/image`).set('Cookie',viewerCookie);
    expect(Buffer.from(editedImage.body).equals(Buffer.from(originalImage.body))).toBe(false);
    const changedRotation=await request(app).get('/ads').set('Cookie',viewerCookie);
    expect(changedRotation.body.find(r=>r.id===first.body.id).revision).toBe(2);
    await request(app).put(`/ads/owner/${second.body.id}`).set('Cookie',ownerCookie).send({...ad,active:false});
    await request(app).delete(`/ads/owner/${first.body.id}`).set('Cookie',ownerCookie);
    expect((await request(app).get('/ads').set('Cookie',viewerCookie)).body).toEqual([]);
    listed=await request(app).get('/ads/owner/list').set('Cookie',ownerCookie);
    expect(listed.body.find(r=>r.id===first.body.id)).toMatchObject({removed:true,stats:{impressions:1,clicks:1,viewers:1}});
  });
});
