import React, { useState, useEffect } from "react";
import { base44 } from "@/api/base44Client";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";
import { MessageSquare, Send, Sparkles, Loader2, CheckCircle2, Mail } from "lucide-react";
import { toast } from "sonner";

const MESSAGE_TYPES = [
  { value: "bug_report", label: "Bug Report", icon: "🐛" },
  { value: "feature_request", label: "Feature Request", icon: "💡" },
  { value: "question", label: "Question", icon: "❓" },
  { value: "feedback", label: "Feedback", icon: "💬" },
  { value: "other", label: "Other", icon: "📝" }
];

export default function ContactSupport() {
  const [user, setUser] = useState(null);
  const [subject, setSubject] = useState("");
  const [message, setMessage] = useState("");
  const [messageType, setMessageType] = useState("other");
  const [isGenerating, setIsGenerating] = useState(false);
  const [isSending, setIsSending] = useState(false);
  const [myMessages, setMyMessages] = useState([]);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    loadUser();
  }, []);

  const loadUser = async () => {
    try {
      const userData = await base44.auth.me();
      setUser(userData);
      await loadMyMessages(userData.id);
    } catch (error) {
      console.error("Error loading user:", error);
    } finally {
      setIsLoading(false);
    }
  };

  const loadMyMessages = async (userId) => {
    try {
      const messages = await base44.entities.Message.filter({ user_id: userId }, '-created_date');
      setMyMessages(messages);
    } catch (error) {
      console.error("Error loading messages:", error);
    }
  };

  const handleAIGenerate = async () => {
    if (!subject.trim()) {
      toast.error("Please enter a subject first");
      return;
    }

    setIsGenerating(true);
    try {
      const prompt = `You are helping a user compose a ${messageType.replace('_', ' ')} message to the app developer (Dr. John White).

Subject: ${subject}

Write a clear, professional message that:
1. Explains the issue or request clearly
2. Provides relevant context
3. Is polite and constructive
4. Is concise (3-5 sentences)

Return only the message text, nothing else.`;

      const response = await base44.integrations.Core.InvokeLLM({
        prompt,
        add_context_from_internet: false
      });

      setMessage(response);
      toast.success("Message generated by AI!");
    } catch (error) {
      toast.error("Failed to generate message");
      console.error(error);
    } finally {
      setIsGenerating(false);
    }
  };

  const handleSend = async () => {
    if (!subject.trim() || !message.trim()) {
      toast.error("Please fill in both subject and message");
      return;
    }

    setIsSending(true);
    try {
      await base44.entities.Message.create({
        user_id: user.id,
        user_email: user.email,
        user_name: user.full_name || user.email,
        subject: subject.trim(),
        message: message.trim(),
        message_type: messageType,
        status: "new"
      });

      toast.success("Message sent to Dr. John White!");
      setSubject("");
      setMessage("");
      setMessageType("other");
      await loadMyMessages(user.id);
    } catch (error) {
      toast.error("Failed to send message");
      console.error(error);
    } finally {
      setIsSending(false);
    }
  };

  const getStatusColor = (status) => {
    switch (status) {
      case "new": return "bg-blue-100 text-blue-800";
      case "in_progress": return "bg-yellow-100 text-yellow-800";
      case "resolved": return "bg-green-100 text-green-800";
      case "closed": return "bg-gray-100 text-gray-800";
      default: return "bg-gray-100 text-gray-800";
    }
  };

  if (isLoading) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <Loader2 className="w-8 h-8 animate-spin text-indigo-600" />
      </div>
    );
  }

  if (!user) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center p-4">
        <Card className="max-w-md">
          <CardHeader>
            <CardTitle>Sign In Required</CardTitle>
            <CardDescription>Please sign in to contact support</CardDescription>
          </CardHeader>
        </Card>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-50 to-gray-100 dark:from-gray-900 dark:to-gray-800 p-4 md:p-8">
      <div className="max-w-4xl mx-auto space-y-6">
        {/* Header */}
        <div>
          <h1 className="text-3xl font-bold flex items-center gap-2">
            <MessageSquare className="w-8 h-8 text-indigo-600" />
            Contact Dr. John White
          </h1>
          <p className="text-gray-600 dark:text-gray-400 mt-2">
            Send a message to the app creator
          </p>
        </div>

        {/* Compose Message */}
        <Card>
          <CardHeader>
            <CardTitle>Send New Message</CardTitle>
            <CardDescription>
              Get help with bugs, request features, or ask questions
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div>
              <label className="block text-sm font-medium mb-2">Message Type</label>
              <Select value={messageType} onValueChange={setMessageType}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {MESSAGE_TYPES.map((type) => (
                    <SelectItem key={type.value} value={type.value}>
                      {type.icon} {type.label}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div>
              <label className="block text-sm font-medium mb-2">Subject</label>
              <Input
                value={subject}
                onChange={(e) => setSubject(e.target.value)}
                placeholder="Brief description of your message"
              />
            </div>

            <div>
              <label className="block text-sm font-medium mb-2">Message</label>
              <Textarea
                value={message}
                onChange={(e) => setMessage(e.target.value)}
                placeholder="Describe your issue, request, or question in detail..."
                rows={6}
              />
            </div>

            <div className="flex gap-2">
              <Button
                variant="outline"
                onClick={handleAIGenerate}
                disabled={isGenerating || !subject.trim()}
                className="flex items-center gap-2"
              >
                {isGenerating ? (
                  <Loader2 className="w-4 h-4 animate-spin" />
                ) : (
                  <Sparkles className="w-4 h-4" />
                )}
                AI Write Message
              </Button>
              <Button
                onClick={handleSend}
                disabled={isSending || !subject.trim() || !message.trim()}
                className="flex items-center gap-2 ml-auto"
              >
                {isSending ? (
                  <Loader2 className="w-4 h-4 animate-spin" />
                ) : (
                  <Send className="w-4 h-4" />
                )}
                Send Message
              </Button>
            </div>
          </CardContent>
        </Card>

        {/* My Messages */}
        {myMessages.length > 0 && (
          <Card>
            <CardHeader>
              <CardTitle>Your Messages</CardTitle>
              <CardDescription>View your conversation history</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                {myMessages.map((msg) => (
                  <div key={msg.id} className="border rounded-lg p-4 space-y-2">
                    <div className="flex items-center justify-between">
                      <h3 className="font-semibold">{msg.subject}</h3>
                      <Badge className={getStatusColor(msg.status)}>
                        {msg.status.replace('_', ' ')}
                      </Badge>
                    </div>
                    <p className="text-sm text-gray-600">{msg.message}</p>
                    <div className="flex items-center gap-2 text-xs text-gray-500">
                      <span>{new Date(msg.created_date).toLocaleDateString()}</span>
                      <span>•</span>
                      <span className="capitalize">{msg.message_type.replace('_', ' ')}</span>
                    </div>
                    {msg.admin_response && (
                      <div className="mt-3 p-3 bg-indigo-50 dark:bg-indigo-900/20 rounded border-l-4 border-indigo-600">
                        <div className="flex items-center gap-2 mb-2">
                          <Mail className="w-4 h-4 text-indigo-600" />
                          <span className="font-semibold text-sm text-indigo-900 dark:text-indigo-100">
                            Dr. John White replied:
                          </span>
                        </div>
                        <p className="text-sm text-indigo-800 dark:text-indigo-200">{msg.admin_response}</p>
                        <p className="text-xs text-indigo-600 mt-2">
                          {new Date(msg.responded_at).toLocaleString()}
                        </p>
                      </div>
                    )}
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        )}
      </div>
    </div>
  );
}