import React, { useState, useEffect } from "react";
import { api } from '@/api/apiClient';
import { useAuth } from '@/lib/AuthContext';
import { logError } from '@/lib/logError';
import { LARRY_SYSTEM_PROMPT } from '@/ai/personas';
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { MessageSquare, Send, Sparkles, Loader2, Mail, Palette } from "lucide-react";
import { toast } from "sonner";

const MESSAGE_TYPES = [
  { value: "bug_report", label: "Bug Report", icon: "🐛" },
  { value: "feature_request", label: "Feature Request", icon: "💡" },
  { value: "question", label: "Question", icon: "❓" },
  { value: "feedback", label: "Feedback", icon: "💬" },
  { value: "other", label: "Other", icon: "📝" }
];

export default function ContactSupport() {
  const { user, isLoadingAuth } = useAuth();
  const [subject, setSubject] = useState("");
  const [message, setMessage] = useState("");
  const [messageType, setMessageType] = useState("other");
  const [isGenerating, setIsGenerating] = useState(false);
  const [isSending, setIsSending] = useState(false);
  const [myMessages, setMyMessages] = useState([]);
  const [isLoading, setIsLoading] = useState(true);
  const [theme, setTheme] = useState({
    accentColor: 'indigo',
    fontSize: 'medium',
    fontFamily: 'sans'
  });

  // Whenever a user resolves from AuthContext, sync theme + messages.
  useEffect(() => {
    if (isLoadingAuth) return;
    if (!user) {
      setIsLoading(false);
      return;
    }
    if (user.message_theme) setTheme(user.message_theme);
    loadMyMessages(user.id)
      .catch((err) => logError('Failed to load support messages', err))
      .finally(() => setIsLoading(false));
  }, [isLoadingAuth, user]);

  const saveThemePreference = async (newTheme) => {
    try {
      await api.auth.updateMe({ message_theme: newTheme });
      setTheme(newTheme);
      toast.success("Theme saved!");
    } catch (error) {
      toast.error("Failed to save theme");
    }
  };

  const loadMyMessages = async (userId) => {
    try {
      const messages = await api.entities.Message.filter({ user_id: userId }, '-created_date');
      setMyMessages(messages);
    } catch (error) {
      console.error("Error loading messages:", error);
    }
  };

  const handleAIGenerate = async () => {
    if (!subject.trim()) {
      toast.error("Please enter a subject first");
      return;
    }

    setIsGenerating(true);
    try {
      const prompt = `You are helping a user compose a ${messageType.replace('_', ' ')} message to the app developer (Dr. John White).

Subject: ${subject}

Write a clear, professional message that:
1. Explains the issue or request clearly
2. Provides relevant context
3. Is polite and constructive
4. Is concise (3-5 sentences)

Return only the message text, nothing else.`;

      const response = await api.integrations.Core.InvokeLLM({
        system_prompt: LARRY_SYSTEM_PROMPT,
        prompt,
        add_context_from_internet: false
      });

      setMessage(response);
      toast.success("Message generated by AI!");
    } catch (error) {
      toast.error("Failed to generate message");
      console.error(error);
    } finally {
      setIsGenerating(false);
    }
  };

  const handleSend = async () => {
    if (!subject.trim() || !message.trim()) {
      toast.error("Please fill in both subject and message");
      return;
    }

    setIsSending(true);
    try {
      await api.entities.Message.create({
        user_id: user.id,
        user_email: user.email,
        user_name: user.full_name || user.email,
        subject: subject.trim(),
        message: message.trim(),
        message_type: messageType,
        status: "new"
      });

      toast.success("Message sent to Dr. John White!");
      setSubject("");
      setMessage("");
      setMessageType("other");
      await loadMyMessages(user.id);
    } catch (error) {
      toast.error("Failed to send message");
      console.error(error);
    } finally {
      setIsSending(false);
    }
  };

  const getStatusColor = (status) => {
    switch (status) {
      case "new": return "bg-blue-100 text-blue-800";
      case "in_progress": return "bg-yellow-100 text-yellow-800";
      case "resolved": return "bg-green-100 text-green-800";
      case "closed": return "bg-gray-100 text-gray-800";
      default: return "bg-gray-100 text-gray-800";
    }
  };

  const colorThemes = {
    indigo: { bg: 'bg-indigo-600', hover: 'hover:bg-indigo-700', border: 'border-indigo-600', text: 'text-indigo-600', lightBg: 'bg-indigo-50' },
    purple: { bg: 'bg-purple-600', hover: 'hover:bg-purple-700', border: 'border-purple-600', text: 'text-purple-600', lightBg: 'bg-purple-50' },
    blue: { bg: 'bg-blue-600', hover: 'hover:bg-blue-700', border: 'border-blue-600', text: 'text-blue-600', lightBg: 'bg-blue-50' },
    green: { bg: 'bg-green-600', hover: 'hover:bg-green-700', border: 'border-green-600', text: 'text-green-600', lightBg: 'bg-green-50' },
    rose: { bg: 'bg-rose-600', hover: 'hover:bg-rose-700', border: 'border-rose-600', text: 'text-rose-600', lightBg: 'bg-rose-50' },
    amber: { bg: 'bg-amber-600', hover: 'hover:bg-amber-700', border: 'border-amber-600', text: 'text-amber-600', lightBg: 'bg-amber-50' }
  };

  const fontSizes = {
    small: 'text-sm',
    medium: 'text-base',
    large: 'text-lg'
  };

  const fontFamilies = {
    sans: 'font-sans',
    serif: 'font-serif',
    mono: 'font-mono'
  };

  const currentTheme = colorThemes[theme.accentColor] || colorThemes.indigo;

  if (isLoading) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <Loader2 className="w-8 h-8 animate-spin text-indigo-600" />
      </div>
    );
  }

  if (!user) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center p-4">
        <Card className="max-w-md">
          <CardHeader>
            <CardTitle>Sign In Required</CardTitle>
            <CardDescription>Please sign in to contact support</CardDescription>
          </CardHeader>
        </Card>
      </div>
    );
  }

  return (
    <div className={`min-h-screen bg-gradient-to-br from-gray-50 to-gray-100 dark:from-gray-900 dark:to-gray-800 p-4 md:p-8 ${fontFamilies[theme.fontFamily]}`}>
      <div className="max-w-4xl mx-auto space-y-6">
        {/* Header */}
        <div className="flex items-center justify-between">
          <div>
            <h1 className={`text-3xl font-bold flex items-center gap-2 ${fontSizes[theme.fontSize]}`}>
              <MessageSquare className={`w-8 h-8 ${currentTheme.text}`} />
              Contact Dr. John White
            </h1>
            <p className="text-gray-600 dark:text-gray-400 mt-2">
              Send a message to the app creator
            </p>
          </div>
          <Popover>
            <PopoverTrigger asChild>
              <Button variant="outline" size="icon">
                <Palette className="w-4 h-4" />
              </Button>
            </PopoverTrigger>
            <PopoverContent className="w-80">
              <div className="space-y-4">
                <h3 className="font-semibold">Customize Appearance</h3>
                
                <div>
                  <label className="text-sm font-medium">Accent Color</label>
                  <div className="grid grid-cols-6 gap-2 mt-2">
                    {Object.keys(colorThemes).map((color) => (
                      <button
                        key={color}
                        onClick={() => saveThemePreference({ ...theme, accentColor: color })}
                        className={`w-8 h-8 rounded-full ${colorThemes[color].bg} ${theme.accentColor === color ? 'ring-2 ring-offset-2 ring-gray-900' : ''}`}
                      />
                    ))}
                  </div>
                </div>

                <div>
                  <label className="text-sm font-medium">Font Size</label>
                  <Select value={theme.fontSize} onValueChange={(value) => saveThemePreference({ ...theme, fontSize: value })}>
                    <SelectTrigger className="mt-2">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="small">Small</SelectItem>
                      <SelectItem value="medium">Medium</SelectItem>
                      <SelectItem value="large">Large</SelectItem>
                    </SelectContent>
                  </Select>
                </div>

                <div>
                  <label className="text-sm font-medium">Font Style</label>
                  <Select value={theme.fontFamily} onValueChange={(value) => saveThemePreference({ ...theme, fontFamily: value })}>
                    <SelectTrigger className="mt-2">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="sans">Sans Serif</SelectItem>
                      <SelectItem value="serif">Serif</SelectItem>
                      <SelectItem value="mono">Monospace</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </div>
            </PopoverContent>
          </Popover>
        </div>

        {/* Compose Message */}
        <Card>
          <CardHeader>
            <CardTitle>Send New Message</CardTitle>
            <CardDescription>
              Get help with bugs, request features, or ask questions
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div>
              <label className="block text-sm font-medium mb-2">Message Type</label>
              <Select value={messageType} onValueChange={setMessageType}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {MESSAGE_TYPES.map((type) => (
                    <SelectItem key={type.value} value={type.value}>
                      {type.icon} {type.label}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div>
              <label className="block text-sm font-medium mb-2">Subject</label>
              <Input
                value={subject}
                onChange={(e) => setSubject(e.target.value)}
                placeholder="Brief description of your message"
              />
            </div>

            <div>
              <label className="block text-sm font-medium mb-2">Message</label>
              <Textarea
                value={message}
                onChange={(e) => setMessage(e.target.value)}
                placeholder="Describe your issue, request, or question in detail..."
                rows={6}
                className={fontSizes[theme.fontSize]}
              />
            </div>

            <div className="flex gap-2">
              {/* Intentionally NOT disabled on empty subject: a disabled
                  button silently swallows the click and gives the user no
                  feedback. handleAIGenerate guards an empty subject and
                  surfaces a "Please enter a subject first" toast instead. */}
              <Button
                variant="outline"
                onClick={handleAIGenerate}
                disabled={isGenerating}
                className="flex items-center gap-2"
              >
                {isGenerating ? (
                  <Loader2 className="w-4 h-4 animate-spin" />
                ) : (
                  <Sparkles className="w-4 h-4" />
                )}
                AI Write Message
              </Button>
              <Button
                onClick={handleSend}
                disabled={isSending}
                className={`flex items-center gap-2 ml-auto ${currentTheme.bg} ${currentTheme.hover} text-white`}
              >
                {isSending ? (
                  <Loader2 className="w-4 h-4 animate-spin" />
                ) : (
                  <Send className="w-4 h-4" />
                )}
                Send Message
              </Button>
            </div>
          </CardContent>
        </Card>

        {/* My Messages */}
        {myMessages.length > 0 && (
          <Card>
            <CardHeader>
              <CardTitle>Your Messages</CardTitle>
              <CardDescription>View your conversation history</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                {myMessages.map((msg) => (
                  <div key={msg.id} className="border rounded-lg p-4 space-y-2">
                    <div className="flex items-center justify-between">
                      <h3 className="font-semibold">{msg.subject}</h3>
                      <Badge className={getStatusColor(msg.status)}>
                        {msg.status.replace('_', ' ')}
                      </Badge>
                    </div>
                    <p className="text-sm text-gray-600">{msg.message}</p>
                    <div className="flex items-center gap-2 text-xs text-gray-500">
                      <span>{new Date(msg.created_date).toLocaleDateString()}</span>
                      <span>•</span>
                      <span className="capitalize">{msg.message_type.replace('_', ' ')}</span>
                    </div>
                    {msg.admin_response && (
                      <div className={`mt-3 p-3 ${currentTheme.lightBg} dark:bg-gray-800 rounded border-l-4 ${currentTheme.border}`}>
                        <div className="flex items-center gap-2 mb-2">
                          <Mail className={`w-4 h-4 ${currentTheme.text}`} />
                          <span className={`font-semibold text-sm ${currentTheme.text}`}>
                            Dr. John White replied:
                          </span>
                        </div>
                        <p className={`${fontSizes[theme.fontSize]} text-gray-700 dark:text-gray-300`}>{msg.admin_response}</p>
                        <p className="text-xs text-gray-500 mt-2">
                          {new Date(msg.responded_at).toLocaleString()}
                        </p>
                      </div>
                    )}
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        )}
      </div>
    </div>
  );
}