/**
 * Exact structured-output contracts used by SermonSmith AI workflows.
 *
 * The browser sends only a contract id. The API resolves that id here and
 * supplies this trusted schema to the model; request bodies never supply a
 * schema or schema-authored instructions. Unknown schemas fail closed in the
 * client adapter, and an id is valid only for its registered workflow.
 *
 * Generated from the production call sites and pinned in source control so a
 * frontend schema change cannot silently alter the server contract.
 */
const CONTRACT_DEFINITIONS = [
  {"id":"bible_maps-30583b048095","feature":"bible_maps","schema":{"type":"object","properties":{"title":{"type":"string"},"description":{"type":"string"},"locations":{"type":"array","items":{"type":"object","properties":{"name":{"type":"string"},"lat":{"type":"number"},"lng":{"type":"number"},"description":{"type":"string"},"scripture":{"type":"string"}}}}}}},
  {"id":"bible_maps-fee2b0048cf6","feature":"bible_maps","schema":{"type":"object","properties":{"title":{"type":"string"},"description":{"type":"string"},"events":{"type":"array","items":{"type":"object","properties":{"event":{"type":"string"},"date":{"type":"string"},"description":{"type":"string"},"scripture":{"type":"string"}}}}}}},
  {"id":"bible_study-251253d7970a","feature":"bible_study","schema":{"type":"object","properties":{"verses":{"type":"array","items":{"type":"string"}}}}},
  {"id":"bible_study-70087a71a27d","feature":"bible_study","schema":{"type":"object","properties":{"studies":{"type":"array","items":{"type":"object","properties":{"title":{"type":"string"},"reason":{"type":"string"}}}}}}},
  {"id":"bible_study-c3fe8b3aa712","feature":"bible_study","schema":{"type":"object","properties":{"questions":{"type":"array","items":{"type":"string"}}}}},
  {"id":"bible_study-c99593fc53d6","feature":"bible_study","schema":{"type":"object","properties":{"title":{"type":"string"},"topic":{"type":"string"},"overview":{"type":"string"},"key_verses":{"type":"array","items":{"type":"string"}},"study_sections":{"type":"array","items":{"type":"object","properties":{"title":{"type":"string"},"scripture":{"type":"string"},"insights":{"type":"string"},"questions":{"type":"array","items":{"type":"string"}},"application":{"type":"string"}}}},"conclusion":{"type":"string"}}}},
  {"id":"ethics-0e35210d50c5","feature":"ethics","schema":{"type":"object","properties":{"pastoral_guidance":{"type":"string"},"common_questions":{"type":"array","items":{"type":"object","properties":{"question":{"type":"string"},"answer":{"type":"string"}}}},"further_reading":{"type":"array","items":{"type":"object","properties":{"title":{"type":"string"},"author":{"type":"string"},"description":{"type":"string"}}}}}}},
  {"id":"ethics-5b7391f79f2b","feature":"ethics","schema":{"type":"object","properties":{"modern_application":{"type":"string"}}}},
  {"id":"ethics-611e60840355","feature":"ethics","schema":{"type":"object","properties":{"topic_title":{"type":"string"},"ethical_category":{"type":"string"},"definition":{"type":"string"},"biblical_foundation":{"type":"object","properties":{"key_scriptures":{"type":"array","items":{"type":"object","properties":{"reference":{"type":"string"},"text":{"type":"string","description":"One-line summary of the verse's relevance — NOT quoted verse text; exact wording must be looked up in a real translation"},"application":{"type":"string"}}}},"theological_principles":{"type":"array","items":{"type":"string"}}}}}}},
  {"id":"ethics-b96576c9b6b3","feature":"ethics","schema":{"type":"object","properties":{"early_church":{"type":"string"},"church_fathers":{"type":"string"},"reformation_era":{"type":"string"},"modern_church":{"type":"string"}}}},
  {"id":"ethics-d0454dae46ea","feature":"ethics","schema":{"type":"object","properties":{"different_views":{"type":"array","items":{"type":"object","properties":{"perspective":{"type":"string"},"reasoning":{"type":"string"},"biblical_support":{"type":"string"}}}}}}},
  {"id":"ethics-e17024ea789f","feature":"ethics","schema":{"type":"object","properties":{"topic_title":{"type":"string"},"perspectives":{"type":"array","items":{"type":"object","properties":{"denomination":{"type":"string"},"position_summary":{"type":"string"},"key_scriptures":{"type":"array","items":{"type":"string"}},"reasoning":{"type":"string"},"pastoral_tone":{"type":"string"},"notable_figures":{"type":"string"}}}},"common_ground":{"type":"string"},"key_differences":{"type":"string"},"pastoral_advice":{"type":"string"}}}},
  {"id":"exegesis-24fe11005316","feature":"exegesis","schema":{"type":"object","properties":{"passage_text":{"type":"string"},"original_language":{"type":"object","properties":{"key_words":{"type":"array","items":{"type":"object","properties":{"word":{"type":"string"},"original":{"type":"string"},"meaning":{"type":"string"},"significance":{"type":"string"}}}},"grammar_notes":{"type":"string"}}},"historical_context":{"type":"object","properties":{"date_author":{"type":"string"},"audience":{"type":"string"},"cultural_background":{"type":"string"},"historical_situation":{"type":"string"}}},"literary_context":{"type":"object","properties":{"surrounding_text":{"type":"string"},"book_structure":{"type":"string"},"genre":{"type":"string"},"literary_devices":{"type":"string"}}},"theological_message":{"type":"object","properties":{"main_point":{"type":"string"},"broader_themes":{"type":"string"},"denominational_view":{"type":"string"},"key_doctrines":{"type":"string"}}},"cross_references":{"type":"array","items":{"type":"object","properties":{"reference":{"type":"string"},"connection":{"type":"string"}}}},"application":{"type":"object","properties":{"original_meaning":{"type":"string"},"contemporary_meaning":{"type":"string"},"misinterpretations":{"type":"string"},"preaching_points":{"type":"array","items":{"type":"string"}}}}}}},
  {"id":"exegesis-cd187105e2a3","feature":"exegesis","schema":{"type":"object","properties":{"related_concepts":{"type":"array","items":{"type":"object","properties":{"concept":{"type":"string"},"explanation":{"type":"string"},"scriptures":{"type":"array","items":{"type":"string"}}}}},"denominational_perspectives":{"type":"array","items":{"type":"object","properties":{"tradition":{"type":"string"},"view":{"type":"string"},"emphasis":{"type":"string"},"biblical_basis":{"type":"string"}}}},"comparative_summary":{"type":"object","properties":{"similarities":{"type":"array","items":{"type":"string"}},"differences":{"type":"array","items":{"type":"object","properties":{"area":{"type":"string"},"description":{"type":"string"}}}}}},"counter_arguments":{"type":"array","items":{"type":"object","properties":{"objection":{"type":"string"},"response":{"type":"string"},"scripture_support":{"type":"string"}}}},"historical_context":{"type":"array","items":{"type":"object","properties":{"period":{"type":"string"},"development":{"type":"string"},"key_figures":{"type":"string"}}}},"practical_implications":{"type":"array","items":{"type":"object","properties":{"area":{"type":"string"},"application":{"type":"string"},"warning":{"type":"string"}}}}}}},
  {"id":"library-81f7826b61ea","feature":"library","schema":{"type":"object","properties":{"recommendations":{"type":"array","items":{"type":"object","properties":{"sermon_id":{"type":"string"},"reason":{"type":"string"}}}}}}},
  {"id":"library-87f8ef8ccdbc","feature":"library","schema":{"type":"object","properties":{"tags":{"type":"array","items":{"type":"string"}}}}},
  {"id":"library-d7349a10e4ef","feature":"library","schema":{"type":"object","properties":{"content_tags":{"type":"array","items":{"type":"string"}},"style_tags":{"type":"array","items":{"type":"string"}},"category":{"type":"string"}}}},
  {"id":"library-e6a99dca98e0","feature":"library","schema":{"type":"object","properties":{"indices":{"type":"array","items":{"type":"number"}},"reasoning":{"type":"string"}}}},
  {"id":"multi_perspective_study-f2f508822ac4","feature":"multi_perspective_study","schema":{"type":"object","properties":{"passage_context":{"type":"object","properties":{"original_language":{"type":"string"},"historical_setting":{"type":"string"},"literary_genre":{"type":"string"},"author_intent":{"type":"string"}}},"perspectives":{"type":"array","items":{"type":"object","properties":{"tradition":{"type":"string"},"interpretation":{"type":"string"},"key_emphasis":{"type":"string"},"distinctive_insight":{"type":"string"},"practical_application":{"type":"string"},"notable_theologians":{"type":"string"},"potential_concerns":{"type":"string"}}}},"common_ground":{"type":"array","items":{"type":"string"}},"key_disagreements":{"type":"array","items":{"type":"object","properties":{"issue":{"type":"string"},"viewpoints":{"type":"string"}}}},"study_questions":{"type":"array","items":{"type":"string"}},"personal_reflection":{"type":"string"}}}},
  {"id":"plan_adaptation-610d108baeb6","feature":"plan_adaptation","schema":{"type":"object","properties":{"name":{"type":"string"},"description":{"type":"string"},"duration_days":{"type":"number"},"daily_readings":{"type":"array","items":{"type":"object","properties":{"day":{"type":"number"},"passages":{"type":"array","items":{"type":"string"}},"reflection":{"type":"string"},"activities":{"type":"array","items":{"type":"object","properties":{"type":{"type":"string"},"description":{"type":"string"}}}},"discussion_questions":{"type":"array","items":{"type":"string"}},"prayer_points":{"type":"array","items":{"type":"string"}}}}}}}},
  {"id":"prayer-7ec2b8892f78","feature":"prayer","schema":{"type":"object","properties":{"title":{"type":"string"},"opening":{"type":"string"},"body_sections":{"type":"array","items":{"type":"object","properties":{"focus":{"type":"string"},"content":{"type":"string"}}}},"closing":{"type":"string"},"scripture_basis":{"type":"array","items":{"type":"string"}},"alternate_endings":{"type":"array","items":{"type":"string"}}}}},
  {"id":"presentation-333db3a0d052","feature":"presentation","schema":{"type":"object","properties":{"suggestion_kind":{"type":"string","description":"One of: transition, scripture, example, question"},"content":{"type":"string","description":"The suggestion itself, ready to use from the pulpit"}},"required":["content"]}},
  {"id":"presentation-78764d49ffb4","feature":"presentation","schema":{"type":"object","properties":{"type":{"type":"string"},"suggestion":{"type":"string"}}}},
  {"id":"presentation-e292f565c109","feature":"presentation","schema":{"type":"object","properties":{"verses":{"type":"array","items":{"type":"object","properties":{"reference":{"type":"string"},"relevance":{"type":"string"}},"required":["reference","relevance"]}}},"required":["verses"]}},
  {"id":"quiz-ffb15b512d8b","feature":"quiz","schema":{"type":"object","properties":{"title":{"type":"string","description":"An engaging title for this quiz"},"questions":{"type":"array","minItems":5,"maxItems":15,"items":{"type":"object","properties":{"question":{"type":"string","description":"The quiz question"},"options":{"type":"array","items":{"type":"string"},"minItems":4,"maxItems":4,"description":"Four multiple choice options"},"correct_answer":{"type":"number","description":"Index of correct answer (0-3)"},"explanation":{"type":"string","description":"Brief explanation of the correct answer"},"scripture_reference":{"type":"string","description":"Relevant Bible verse reference"}},"required":["question","options","correct_answer","explanation","scripture_reference"]}}},"required":["title","questions"]}},
  {"id":"reader_insight-0bf08c2e5655","feature":"reader_insight","schema":{"type":"object","properties":{"why_today":{"type":"string"},"reflection":{"type":"string"},"application":{"type":"string"},"prayer_starter":{"type":"string"}}}},
  {"id":"reader_insight-0f082eccb566","feature":"reader_insight","schema":{"type":"object","properties":{"historical_context":{"type":"string"},"literary_context":{"type":"string"},"key_terms":{"type":"array","items":{"type":"string"}},"theological_themes":{"type":"array","items":{"type":"string"}},"cross_references":{"type":"array","items":{"type":"string"}},"life_application":{"type":"string"},"discussion_points":{"type":"array","items":{"type":"string"}}}}},
  {"id":"reader_insight-59f906ae1eec","feature":"reader_insight","schema":{"type":"object","properties":{"historical_context":{"type":"string"},"meaning":{"type":"string"},"application":{"type":"string"},"key_insights":{"type":"string"},"cross_references":{"type":"string"}}}},
  {"id":"reader_insight-7bee1d80c429","feature":"reader_insight","schema":{"type":"object","properties":{"catholic":{"type":"object","properties":{"interpretation":{"type":"string"},"emphasis":{"type":"string"},"practice":{"type":"string"}}},"protestant_reformed":{"type":"object","properties":{"interpretation":{"type":"string"},"emphasis":{"type":"string"},"practice":{"type":"string"}}},"evangelical":{"type":"object","properties":{"interpretation":{"type":"string"},"emphasis":{"type":"string"},"practice":{"type":"string"}}},"eastern_orthodox":{"type":"object","properties":{"interpretation":{"type":"string"},"emphasis":{"type":"string"},"practice":{"type":"string"}}},"pentecostal":{"type":"object","properties":{"interpretation":{"type":"string"},"emphasis":{"type":"string"},"practice":{"type":"string"}}},"liberal_progressive":{"type":"object","properties":{"interpretation":{"type":"string"},"emphasis":{"type":"string"},"practice":{"type":"string"}}},"common_ground":{"type":"string"},"key_differences":{"type":"string"}}}},
  {"id":"reader_insight-9e96f56948dd","feature":"reader_insight","schema":{"type":"object","properties":{"gospel_connection":{"type":"string"},"old_testament_echoes":{"type":"array","items":{"type":"string"}},"new_testament_parallels":{"type":"array","items":{"type":"string"}},"theological_traditions":{"type":"string"},"systematic_theology":{"type":"array","items":{"type":"string"}},"practical_discipleship":{"type":"string"}}}},
  {"id":"reader_insight-d62a3faab168","feature":"reader_insight","schema":{"type":"object","properties":{"original_meaning":{"type":"string"},"what_we_miss":{"type":"string"},"core_truth":{"type":"string"},"misinterpretations":{"type":"string"},"devotional":{"type":"string"},"memorization_tip":{"type":"string"}}}},
  {"id":"reader_insight-e139f728c472","feature":"reader_insight","schema":{"type":"object","properties":{"key_differences":{"type":"string"},"linguistic_analysis":{"type":"string"},"theological_implications":{"type":"string"},"original_language":{"type":"string"},"recommendation":{"type":"string"}}}},
  {"id":"reader_insight-f322dcc6da50","feature":"reader_insight","schema":{"type":"object","properties":{"questions":{"type":"array","items":{"type":"object","properties":{"question":{"type":"string"},"type":{"type":"string"},"difficulty":{"type":"string"}}}}}}},
  {"id":"reader_insight-ff963e972a06","feature":"reader_insight","schema":{"type":"object","properties":{"direct_references":{"type":"array","items":{"type":"object","properties":{"reference":{"type":"string"},"text_snippet":{"type":"string"},"connection":{"type":"string"},"type":{"type":"string"}}}},"thematic_connections":{"type":"array","items":{"type":"object","properties":{"reference":{"type":"string"},"text_snippet":{"type":"string"},"connection":{"type":"string"},"theme":{"type":"string"}}}},"contextual_passages":{"type":"array","items":{"type":"object","properties":{"reference":{"type":"string"},"text_snippet":{"type":"string"},"connection":{"type":"string"}}}},"practical_connections":{"type":"array","items":{"type":"object","properties":{"reference":{"type":"string"},"text_snippet":{"type":"string"},"connection":{"type":"string"}}}}}}},
  {"id":"sermon_adaptation-02ab7e9b9a54","feature":"sermon_adaptation","schema":{"type":"object","properties":{"title":{"type":"string"},"big_idea":{"type":"string"},"points":{"type":"array","items":{"type":"object","properties":{"title":{"type":"string"},"exegesis":{"type":"string"},"illustration":{"type":"string"},"application":{"type":"string"},"supporting_scriptures":{"type":"array","items":{"type":"string"}}}}}}}},
  {"id":"sermon_adaptation-21c6ca2f932d","feature":"sermon_adaptation","schema":{"type":"object","properties":{"title":{"type":"string"},"big_idea":{"type":"string"},"points":{"type":"array","items":{"type":"object","properties":{"title":{"type":"string"},"exegesis":{"type":"string"},"illustration":{"type":"string"},"application":{"type":"string"},"supporting_scriptures":{"type":"array","items":{"type":"string"}}}}},"conclusion":{"type":"string"}}}},
  {"id":"sermon_adaptation-32336dd56c57","feature":"sermon_adaptation","schema":{"type":"object","properties":{"tweets":{"type":"array","items":{"type":"string"}}}}},
  {"id":"sermon_helper-251253d7970a","feature":"sermon_helper","schema":{"type":"object","properties":{"verses":{"type":"array","items":{"type":"string"}}}}},
  {"id":"sermon_helper-8ce791af7263","feature":"sermon_helper","schema":{"type":"object","properties":{"title":{"type":"string"},"big_idea":{"type":"string"},"theological_notes":{"type":"string"},"points":{"type":"array","items":{"type":"object","properties":{"title":{"type":"string"},"exegesis":{"type":"string"},"illustration":{"type":"string"},"application":{"type":"string"},"supporting_scriptures":{"type":"array","items":{"type":"string"}}}}},"conclusion":{"type":"string"}}}},
  {"id":"sermon_helper-b14b4b740f61","feature":"sermon_helper","schema":{"type":"object","properties":{"passages":{"type":"array","items":{"type":"object","properties":{"reference":{"type":"string"},"reason":{"type":"string"}}}}}}},
  {"id":"sermon_outline-ebe09519c27d","feature":"sermon_outline","schema":{"type":"object","properties":{"title":{"type":"string"},"big_idea":{"type":"string"},"main_points":{"type":"array","items":{"type":"object","properties":{"number":{"type":"number"},"title":{"type":"string"},"explanation":{"type":"string"},"significance":{"type":"string"},"supporting_scriptures":{"type":"array","items":{"type":"string"}},"applications":{"type":"array","items":{"type":"object","properties":{"area":{"type":"string"},"action":{"type":"string"},"reflection_question":{"type":"string"}}}},"illustration_suggestions":{"type":"array","items":{"type":"object","properties":{"type":{"type":"string"},"idea":{"type":"string"}}}}}}},"conclusion":{"type":"object","properties":{"recap":{"type":"string"},"call_to_action":{"type":"string"},"final_illustration_idea":{"type":"string"},"invitation":{"type":"string"},"next_steps":{"type":"array","items":{"type":"string"}}}}},"required":["title","big_idea","main_points","conclusion"]}},
  {"id":"sermon_series-c1ef32196e2f","feature":"sermon_series","schema":{"type":"object","properties":{"title":{"type":"string"},"big_idea":{"type":"string"},"series_connection":{"type":"string"},"points":{"type":"array","items":{"type":"object","properties":{"title":{"type":"string"},"exegesis":{"type":"string"},"illustration":{"type":"string"},"application":{"type":"string"},"supporting_scriptures":{"type":"array","items":{"type":"string"}}}}},"conclusion":{"type":"string"},"next_week_teaser":{"type":"string"}}}},
  {"id":"sermon_series-cec8540e9f1e","feature":"sermon_series","schema":{"type":"object","properties":{"series_title":{"type":"string"},"series_description":{"type":"string"},"series_goal":{"type":"string"},"target_audience":{"type":"string"},"theological_trajectory":{"type":"object","properties":{"progression":{"type":"string"},"key_doctrines":{"type":"array","items":{"type":"string"}},"build_pattern":{"type":"string"},"culmination":{"type":"string"},"biblical_connection":{"type":"string"}}},"sermons":{"type":"array","items":{"type":"object","properties":{"week":{"type":"number"},"title":{"type":"string"},"scripture":{"type":"string"},"big_idea":{"type":"string"},"theological_focus":{"type":"string"},"builds_on_previous":{"type":"string"},"preview_next":{"type":"string"},"discussion_questions":{"type":"array","items":{"type":"string"}}}}},"promotion":{"type":"object","properties":{"social_tagline":{"type":"string"},"bulletin_text":{"type":"string"},"email_text":{"type":"string"}}}}}},
  {"id":"sermon-8ce791af7263","feature":"sermon","schema":{"type":"object","properties":{"title":{"type":"string"},"big_idea":{"type":"string"},"theological_notes":{"type":"string"},"points":{"type":"array","items":{"type":"object","properties":{"title":{"type":"string"},"exegesis":{"type":"string"},"illustration":{"type":"string"},"application":{"type":"string"},"supporting_scriptures":{"type":"array","items":{"type":"string"}}}}},"conclusion":{"type":"string"}}}},
  {"id":"study_plan-38c245e1f769","feature":"study_plan","schema":{"type":"object","properties":{"plan_title":{"type":"string"},"plan_overview":{"type":"string"},"daily_lessons":{"type":"array","items":{"type":"object","properties":{"day":{"type":"number"},"title":{"type":"string"},"scripture_reading":{"type":"array","items":{"type":"string"}},"key_verse":{"type":"string"},"devotional_context":{"type":"string"},"activities":{"type":"array","items":{"type":"object","properties":{"type":{"type":"string"},"description":{"type":"string"}}}},"discussion_questions":{"type":"array","items":{"type":"string"}},"prayer_points":{"type":"array","items":{"type":"string"}}}}}}}},
  {"id":"study_plan-dac9b623e797","feature":"study_plan","schema":{"type":"object","properties":{"daily_lessons":{"type":"array","items":{"type":"object","properties":{"day":{"type":"number"},"title":{"type":"string"},"scripture_reading":{"type":"array","items":{"type":"string"}},"key_verse":{"type":"string"},"devotional_context":{"type":"string"},"activities":{"type":"array","items":{"type":"object","properties":{"type":{"type":"string"},"description":{"type":"string"}}}},"discussion_questions":{"type":"array","items":{"type":"string"}},"prayer_points":{"type":"array","items":{"type":"string"}}}}}}}},
  {"id":"thematic_linker-13d7fc045a80","feature":"thematic_linker","schema":{"type":"object","properties":{"indices":{"type":"array","items":{"type":"number"}}}}},
  {"id":"thematic_linker-56234ad9a303","feature":"thematic_linker","schema":{"type":"object","properties":{"primary_themes":{"type":"array","items":{"type":"string"}},"sermon_topics":{"type":"array","items":{"type":"string"}},"life_applications":{"type":"array","items":{"type":"string"}},"related_passages":{"type":"array","items":{"type":"object","properties":{"reference":{"type":"string"},"connection":{"type":"string"}}}},"key_verses":{"type":"array","items":{"type":"object","properties":{"reference":{"type":"string"},"relevance":{"type":"string"}}}},"life_stages":{"type":"array","items":{"type":"string"}},"study_plan_topics":{"type":"array","items":{"type":"string"}},"related_plan_topics":{"type":"array","items":{"type":"string"}}}}},
  {"id":"worldview-345b30eba860","feature":"worldview","schema":{"type":"object","properties":{"core_beliefs":{"type":"array","items":{"type":"object","properties":{"belief":{"type":"string"},"explanation":{"type":"string"}}}},"why_they_believe":{"type":"object","properties":{"philosophical_reasons":{"type":"array","items":{"type":"string"}},"cultural_reasons":{"type":"array","items":{"type":"string"}},"experiential_reasons":{"type":"array","items":{"type":"string"}}}},"christian_comparison":{"type":"object","properties":{"similarities":{"type":"array","items":{"type":"string"}},"key_differences":{"type":"array","items":{"type":"string"}},"common_ground":{"type":"string"}}},"historical_influence":{"type":"object","properties":{"on_christianity":{"type":"string"},"from_christianity":{"type":"string"},"cultural_exchange":{"type":"string"}}},"biblical_perspective":{"type":"object","properties":{"relevant_scriptures":{"type":"array","items":{"type":"object","properties":{"reference":{"type":"string"},"relevance":{"type":"string"}}}},"theological_response":{"type":"string"}}},"apologetics":{"type":"array","items":{"type":"object","properties":{"question":{"type":"string"},"christian_response":{"type":"string"},"scripture_support":{"type":"string"}}}},"engagement_tips":{"type":"array","items":{"type":"string"}}}}},
  {"id":"worldview-629e5bd6e88d","feature":"worldview","schema":{"type":"object","properties":{"similarities":{"type":"array","items":{"type":"string"}},"differences":{"type":"array","items":{"type":"object","properties":{"aspect":{"type":"string"},"system_a":{"type":"string"},"system_b":{"type":"string"}}}},"christian_evaluation":{"type":"string"},"historical_relationship":{"type":"string"},"evangelism_strategy":{"type":"object","properties":{"approach_to_a":{"type":"string"},"approach_to_b":{"type":"string"},"common_bridges":{"type":"array","items":{"type":"string"}}}}}}},
];

function canonicalize(value) {
  if (Array.isArray(value)) return `[${value.map(canonicalize).join(',')}]`;
  if (value && typeof value === 'object') {
    const body = Object.keys(value)
      .sort()
      .map((key) => `${JSON.stringify(key)}:${canonicalize(value[key])}`)
      .join(',');
    return `{${body}}`;
  }
  return JSON.stringify(value);
}

function deepFreeze(value) {
  if (!value || typeof value !== 'object' || Object.isFrozen(value)) return value;
  for (const nested of Object.values(value)) deepFreeze(nested);
  return Object.freeze(value);
}

const byId = new Map();
const byFeatureAndSchema = new Map();
for (const definition of CONTRACT_DEFINITIONS) {
  deepFreeze(definition.schema);
  Object.freeze(definition);
  byId.set(definition.id, definition);
  byFeatureAndSchema.set(`${definition.feature}:${canonicalize(definition.schema)}`, definition.id);
}

export const AI_OUTPUT_CONTRACTS = Object.freeze(CONTRACT_DEFINITIONS);

export function outputContractFor(feature, schema) {
  if (!feature || !schema || typeof schema !== 'object') return null;
  return byFeatureAndSchema.get(`${feature}:${canonicalize(schema)}`) || null;
}

export function outputSchemaForContract(feature, contractId) {
  const definition = byId.get(contractId);
  return definition?.feature === feature ? definition.schema : null;
}

export function defaultOutputContractForFeature(feature) {
  const matches = CONTRACT_DEFINITIONS.filter((definition) => definition.feature === feature);
  return matches.length === 1 ? matches[0].id : null;
}
